name: Run platformos-check on Liquid files
on:
  push:
    paths-ignore:
      - '**/README.md'
  pull_request:
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  run-platformos-check:
    uses: Platform-OS/gh-workflows/.github/workflows/run_platformos_check_reusable.yml@main
