name: Run platformos-check on Liquid files
on:
  push:
    paths-ignore:
      - '**/README.md'
  pull_request:
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  run-platformos-check:
    uses: Platform-OS/gh-workflows/.github/workflows/run-platformos-check.yml@1414c715c98987d4ff35b2b7c949c58712a8d97f
