name: Run platformos-check on Liquid files
on:
  push:
    paths-ignore:
      - '**/README.md'
  pull_request:
    paths-ignore:
      - '**/README.md'

jobs:
  check_liquid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up logs directory
        run: |
          mkdir -p logs
          chmod -R 777 logs

      - name: Start PlatformOS LSP
        id: start_lsp
        run: |
          docker run -i \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLATFORMOS_CHECK_DEBUG=true \
            -e PLATFORMOS_CHECK_DEBUG_LOG_FILE=${{ github.workspace }}/logs/platformos-lsp.log \
            platformos/platformos-lsp:latest

      - name: Run platformos-check
        id: run_check
        if: ${{ steps.start_lsp.outcome == 'success' }}
        continue-on-error: true
        run: |
          set -o pipefail
          docker run -i \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLATFORMOS_CHECK_DEBUG=true \
            -e PLATFORMOS_CHECK_DEBUG_LOG_FILE=${{ github.workspace }}/logs/platformos-check.log \
            platformos/platformos-check:latest -o json | jq . | tee logs/platformos-check.json

      - name: Upload logs
        if: ${{ steps.run_check.outcome == 'success' || steps.run_check.outcome == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: platformos_check_logs_${{ github.run_id }}
          path: |
            logs/platformos-lsp.log
            logs/platformos-check.json

      - name: Summary of platformos-check
        if: ${{ steps.run_check.outcome == 'success' || steps.run_check.outcome == 'failure' }}
        run: |
          echo "# Summary :checkered_flag:" >> $GITHUB_STEP_SUMMARY
          echo "## Result: ${{ steps.run_check.outcome }} ${{ env.result-icon }}" >> $GITHUB_STEP_SUMMARY
        env:
          result-icon: ${{ steps.run_check.outcome == 'success' && ':white_check_mark:' || ':x:' }}

      - name: Fail job if platformos-check failed
        if: ${{ steps.run_check.outcome == 'failure' }}
        run: |
          echo "platformos-check failed — marking job as failed"
          exit 1
