name: TestAndBuild 

on:
  push:
    branches: [ workflow-and-tests ]
  workflow_dispatch:

jobs:
  call-test-workflow:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  #call-release-workflow:
  #  uses: ./.github/workflows/release.yml
  #  needs: call-test-workflow
  #  secrets: inherit

