name: TestAndBuild 

on:
  push:
    branches: [ workflow-and-tests ]
  workflow_dispatch:

jobs:
  call-test-workflow:
    uses: ./.github/workflows/test.yml
    if: ${{ inputs.run-tests }}
    with:
      module_root: ./modules/core
      run-tests: true
    secrets: inherit
  call-release-workflow:
    uses: ./.github/workflows/release.yml
    needs: call-test-workflow
    if: ${{ inputs.release }}
    with:
      release: false
    secrets: inherit

