name: TestAndBuild 

on:
  push:
    branches: [ workflow-and-tests ]
  workflow_dispatch:

jobs:
  call-test-workflow:
    uses: Platform-OS/pos-module-gh-workflows/.github/workflows/test.yml@main
    secrets: inherit
  #call-release-workflow:
  # uses: Platform-OS/pos-module-gh-workflows/.github/workflows/release.yml@main
  # needs: call-test-workflow
  # secrets: inherit

